### ISSUE TITLE
Python: KeyError during build

### ISSUE THREAD

**Issue by iSOLveIT** [jbms/sphinx-immaterial#101]
Sphinx documentation doesn't build and it produces this error message if I use Sphinx-Immaterial as the html_theme:
```python

Exception occurred:
  File "/home/isolveit/Documents/myCodes/Codes/useBlocks/sphinxcontrib-needs/.venv/lib/python3.9/site-packages/sphinx_immaterial/python_domain_fixes.py", line 500, in cross_link_single_parameter
    py.data["synopses"][param_symbol] = synopsis
KeyError: 'synopses'
```

**Comment by 2bndy5** [comment]
Did you also add `sphinx_immaterial` to the `extensions` list  in conf.py?

**Comment by iSOLveIT** [comment]
Just realised I didn't add `sphinx_immaterial` to the `extensions` list in conf.py. 
It is building now. Thanks for the help.

**Comment by 2bndy5** [comment]
Maybe we can try to catch an exception and augment the error message. Maybe create some kind of assertion from Jinja context processing.

**Comment by jbms** [comment]
I am actually a bit confused how this code is even running if `sphinx_immaterial` is not added as an extension.

@iSOLveIT 
What was your theme / extension config when the problem occurred?

**Comment by iSOLveIT** [comment]
In my **conf.py** file, I set the `html_theme` variable using this: `os.getenv('THEME', 'ala aster')`.

As a result, although _sphinx-immaterial_ wasn't included in the `extensions` list, it was used by Sphinx.
