### ISSUE TITLE
Add support for dirhtml builder

### ISSUE THREAD

**Issue by duncanmmacleod** [jbms/sphinx-immaterial#110]
It would be great to get support for the `dirhtml` builder, which I use to replicate the default `mkdocs` behvaiour (turns `doc.rst` into `doc/index.html`, etc).

Naively, it looks like the following patch might be all that is required:

```patch
$ git diff
diff --git a/sphinx_immaterial/__init__.py b/sphinx_immaterial/__init__.py
index d3005c8..eca458a 100644
--- a/sphinx_immaterial/__init__.py
+++ b/sphinx_immaterial/__init__.py
@@ -321,6 +321,7 @@ def setup(app):
     )

     app.add_builder(_get_html_builder(app.registry.builders["html"]), override=True)
+    app.add_builder(_get_html_builder(app.registry.builders["dirhtml"]), override=True)
     app.add_html_theme("sphinx_immaterial", os.path.abspath(os.path.dirname(__file__)))

     # register our custom adminition directive that are tied to the theme's CSS
```

I am happy to post a PR with that if there are no objections.

**Comment by 2bndy5** [comment]
Have a look at me [nav_adapt.py](https://github.com/jbms/sphinx-immaterial/blob/main/sphinx_immaterial/nav_adapt.py). The sphinx structured toc is translated into a mkdocs structured toc.
