### ISSUE TITLE
Google Fonts are loaded from remote server

### ISSUE THREAD

**Issue by jbms** [jbms/sphinx-immaterial#111]
Currently, this theme references Google Fonts from the Google server (inherited from mkdocs-material).

However, that means even a local copy of the built documentation still requires network access to obtain the fonts.

It would be better if the fonts could somehow be fetched/cached when building the documentation so that the built docs have no outside dependencies.

**Comment by 2bndy5** [comment]
Google fonts are hosted from [their own dedicated repo](https://github.com/google/fonts). Downloading them all can add an upward of 600 MB to the distribution. And then there's the problem that Google seems to update them whenever they want without notice (and often not tagging the changes).

Luckily, there seems to be a project that provides the fonts via npm called [fontsource](https://github.com/fontsource/fontsource). Maybe that can be used to better solve this issue.

**Comment by 2bndy5** [comment]
Have you thought about taking this upstream? I wonder if squidfunk would be keen on the idea. There's still the fetching of  mermaid.js to consider.

**Comment by jbms** [comment]
Yes, we wouldn't want to include all 600MB of fonts as part of the PyPI package.  I think it would be better if as part of the documentation build (as opposed to the sphinx-immaterial package build), the fonts selected by the user were downloaded if not already cached and copied into the output directory.

Possibly mkdocs-material would also be interested in solving this issue, although I think they are less concerned about references external resources.  Also since the solution would happen at documentation build time, it would be specific to sphinx or mkdocs.

**Comment by squidfunk** [comment]
[We already solved this 4 months ago](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin)! 😊

**Comment by 2bndy5** [comment]
We seem to building a growing list of features available to insiders; #61, #58, #56, and now this -- not a bad sign for us, but a competitive edge vs upstream public releases.

---

Unfortunately, I doubt we can solve this with an existing Sphinx ext because this theme is a rather unorthodox Sphinx theme (to keep faithful to upstream src).

**Comment by squidfunk** [comment]
Linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) have been released with [8.3.0](https://squidfunk.github.io/mkdocs-material/changelog/#8.3.0) when the last funding goal was reached.

**Comment by 2bndy5** [comment]
fixed in v0.9.0
