### ISSUE TITLE
[build log] parsed JSON schema index is base 0 (not base 1)

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#118]
Opening this as a reminder. Notice the total number does not correspond with the index number in the following log statements:
```
[0/2] Loading JSON schema: apidoc/json/index_transform_schema.yml
[1/2] Loading JSON schema: apidoc/json/inheritance_schema.yml
```
https://github.com/jbms/sphinx-immaterial/blob/b27258e2e6c13eef42df21bf05eaeede4096c517/sphinx_immaterial/apidoc/json/domain.py#L262
should be 
```py
        logger.info("[%d/%d] Loading JSON schema: %s", i + 1, len(all_paths), path)
```

**Comment by jbms** [comment]
I agree, changing to one-based is reasonable.
