### ISSUE TITLE
allow consecutive builds

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#12]
Due to the altered search system in this theme, any consecutive attempt to build docs results in the following error:
```
Exception occurred:
  File "/path/to/env/lib/python3.10/site-packages/sphinx/search/__init__.py", line 283, in load
    index2fn = frozen['docnames']
KeyError: 'docnames'
```
The current workaround is delete any previously built docs (specific to the project being worked on), then re-build the docs.

This affects IDE extensions designed to generate previews of documentation. I don't see a way to workaround this error in the vscode restructuredtext extension, so it would be nice to have this theme cooperate better with sphinx in this scenario.

**Comment by 2bndy5** [comment]
@jbms I tried merging in updates from upstream (v8.2.5...v8.2.8), but I started getting an error (locally and in CI):
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

I think the amount of icons has increased so much that the tools/build/index.ts cannot complete.
[The full traceback in CI logs](https://github.com/jbms/sphinx-immaterial/runs/5782421014?check_suite_focus=true#step:12:37)

**Comment by jbms** [comment]
It looks like the error is actually triggered by the call to esbuild, which generates the javascript bundle (and is unrelated to the icons).

Can you reproduce this problem in the mkdocs-material repository?

I see that this PR upgrades esbuild --- you could try downgrading esbuild to the version we used previously.

**Comment by 2bndy5** [comment]
Reverting the esbuild version back to `^0.14.23` didn't solve the error.

I cannot reproduce the error in mkdocs-material repo (using latest commit).

**Comment by jbms** [comment]
Potentially you could diagnose the problem by bisecting --- attempt a smaller upgrade (i.e. to an older revision of mkdocs-material), verify that it builds, then incrementally upgrade more until you find the culprit.

**Comment by jbms** [comment]
Perhaps this is related to:
https://github.com/squidfunk/mkdocs-material/commit/00f40928cffc6524940ccb1895c86d535dbb3124

**Comment by 2bndy5** [comment]
I'm committing my changes on the more-extensions branch, then I'll switch over to the update-v8.2.8 branch and start investigating. Is the JS traceback even useful (IDK how to read that - yet)?

**Comment by jbms** [comment]
No the traceback isn't really helpful --- it just indicates excessive memory usage but doesn't indicate anything about the cause.  I thought it was esbuild related since the crash happens while esbuild is running but I think esbuild and css bundling happen concurrently.

**Comment by 2bndy5** [comment]
Well, I found that reverting all changes to the pkg.json builds successfully. I'm still having trouble narrowing it down. I think this is an opportunity to learn how to debug mem consumption during script execution.

**Comment by jbms** [comment]
Did you try pulling in a newer version of mkdocs-material that reverts the upgrade to cssnano (from the commit I referenced)?

**Comment by 2bndy5** [comment]
Well not exactly. I was still using the v8.2.8 tag as a source-ref, but I did go through and change the versions to what was used in that commit. It still caused the error.

**Comment by 2bndy5** [comment]
I just tried merging in updates from v8.2.11, and I'm still getting the fatal error from `npm run build`.

**Comment by jbms** [comment]
Did you create a branch that I can take a look at?

**Comment by 2bndy5** [comment]
I did, but I haven't pushed anything. Pushing now. Its on https://github.com/jbms/sphinx-immaterial/tree/merge-upstream-v8.2.11
