### ISSUE TITLE
absent top border in hamburger menu for the active item

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#121]
I've noticed that since resolving #58, the active item in the hamburger menu is missing the top border.
![image](https://user-images.githubusercontent.com/14963867/178421864-6cc963e2-de62-4e6a-a24d-c6eb80a614ce.png)

Because I'm not entirely familiar with the solution for #58, I'm not really sure how to fix this.

**Comment by jbms** [comment]
That's odd --- did you rebuild the bundles?

**Comment by 2bndy5** [comment]
yeah, I did it locally when I noticed it from checking #124

**Comment by 2bndy5** [comment]
I think the specificity issue here, but I can't figure out how the problem didn't show in #121 CI. Maybe I resized my window since then...

**Comment by 2bndy5** [comment]
Nevermind, it was an old rendering from a different builder. I just browsed to the wrong build folder.

**Comment by 2bndy5** [comment]
I have to say, thank you for fixing the windows builds; it goes much faster now (WSL is annoyingly sluggish).
