### ISSUE TITLE
Issue with `python_transform_type_annotations_pep604` not adding `|` correctly

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#127]
I'm observing some issues with `python_transform_type_annotations_pep604`. There are times when `Union[a, b]` isn't converted to `a | b` but rather `a, b`. The same happens when wrapping in an `Optional[]` type hint.

Here is a reproducible `foo` project. I'm testing with current main (00c681084ef9ec4be3a936d30367f64802bc7854).

[foo-example.zip](https://github.com/jbms/sphinx-immaterial/files/9102329/foo-example.zip)

```python
def multiplication(x: Union[int, float], y: int) -> float:
```

![image](https://user-images.githubusercontent.com/12112573/178737970-0cc0805b-6d03-4524-beef-720624c2de04.png)

```python
def func(x: int, y: Optional[Union[int, float]] = None) -> int:
```

![image](https://user-images.githubusercontent.com/12112573/178737934-58f59c99-f2b9-4397-8fa0-a7c07826541c.png)

**Comment by jbms** [comment]
I'm not able to reproduce this with Python 3.9, but it may be python version dependent.

**Comment by jbms** [comment]
Yes, I see that it fails on Python 3.8 --- will have to look into it.

**Comment by jbms** [comment]
https://github.com/jbms/sphinx-immaterial/runs/7328963050?check_suite_focus=true
