### ISSUE TITLE
CSS for details/summary html tags is tied to admonitions' CSS

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#15]
Sphinx and rST directives don't support HTML's `details` and `summary` tags, This theme has some css specifically for these tags which collides with other sphinx extensions that implement custom directives to enumerate the `details` & `summary` tags. Example using `sphinx-panels` (same result from using `sphinx-design`):
### closed
![image](https://user-images.githubusercontent.com/14963867/137846976-7c361240-cc2a-4ace-8185-36f1d5fcf5a3.png)
### open
![image](https://user-images.githubusercontent.com/14963867/137847783-5853de3b-901c-45fd-9ae7-3719d3dea2ed.png)

Notice that the theme's css also assume any generic `.. admonition::` is a `.. note::` which impedes user-defined admonitions.

### code to reproduce
Enable the extension in docs' _conf.py_
```py
extensions = [
    "spinx_immaterial",
    "sphinx_panels",
]
```
Use the extension's introduced directives
```rst

.. dropdown:: Settings used in this documentation

    .. literalinclude:: ./conf.py
        :start-at: # -- HTML theme settings ------------------------------------------------
        :end-before: # ---- Other documentation options -------------------------
```

**Comment by jbms** [comment]
I suppose in this case `sphinx_panels` is also providing its own CSS that conflicts with what is provided by mkdocs-material?

**Comment by 2bndy5** [comment]
Yes. I thought about how to fix this, and concluded that it would be easier to let the styling be done by sphinx extensions (there are other extensions that do the same task). If my conclusion conflicts with keeping faithful to mkdocs-material, then I'm open to other ideas. I just didn't want to go down that rabbit hole of supporting a specific extension(s).

**Comment by 2bndy5** [comment]
I suppose we could create our own directive called `.. material-dropdown::` for this theme. That way we could keep faithful to mkdocs-material and avoid conflicting any sphinx extension's CSS (I think).

**Comment by 2bndy5** [comment]
>Notice that the theme's css also assume any generic `.. admonition::` is a `.. note::` which impedes user-defined admonitions.

In researching this, I found that this CSS choice is born from the deviation of the admonitions markdown extension. However, I also found that we can take advantage of all admonitions supported by mkdocs-material theme using the `:class:` option of the generic `.. admonition::` directive.
```rst
.. admonition:: Abstract
   :class: abstract
   
   This admonition's CSS styling is inherited from the mkdocs-material src.
```
renders as 
![image](https://user-images.githubusercontent.com/14963867/139804634-4888d465-2640-478b-94fd-a7065a364807.png)

Couple this info with my findings in #5 , and we can mimic md-ext admonitions with no changes to mkdocs-material src folder.

I'm posting this here as this info will be added to the docs changes which will be included in the PR to solve this issue.

---
BTW, I'll added a directive to the theme called `.. material-dropdown::` which does avoid any CSS conflicts with a sphinx extension that adds its own CSS for `<details>` & `<summary>` tags. I tested this locally and have the OP snippet rendering as
![image](https://user-images.githubusercontent.com/14963867/139806075-01fdc416-e104-423a-b241-48e46627db4f.png)

**Comment by 2bndy5** [comment]
this solution was undone with the latest merger from upstream (#34). It is no longer a 1 line fix since upstream CSS now uses
```scss
:is(.adomition, details) {
  // ...
}
:is(.admonition-title, summary) {
  // ...
}
```
in several places within the [_adminition.scss](https://github.com/jbms/sphinx-immaterial/blob/6ceccff8d865208ffbdbbe5feef814936d659835/src/assets/stylesheets/main/extensions/markdown/_admonition.scss).

It isn't as bad as it was originally...
### after #34 
![image](https://user-images.githubusercontent.com/14963867/158366358-22f9d4ba-673e-48d6-8f8c-80424721f873.png)
### before #34
![image](https://user-images.githubusercontent.com/14963867/158366946-683b526f-f176-43fe-9841-3d68964ba4a6.png)

**Comment by 2bndy5** [comment]
I'm back to the idea of using a baked in directive that makes proper use of mkdocs-material CSS for details & summary elements.

Instead of including a copy of `sphinxcontrib.details.directive`, we could specify it as a required extension during theme install. Then the theme's `__init__.py` just needs to `setup()` the extension. This is because we now have a separate directive that allows no title in admonitions. Originally, I was trying to kill 2 birds with 1 stone by modifying the `sphinxcontrib.details.directive` to allow for no title.

**Comment by jbms** [comment]
Is there a need to make it a required extension, or could we just have it as an optional dependency?  E.g. have a `sphinx_immaterial.details` module (still part of this same package) that can be added by users as a separate extension?

**Comment by 2bndy5** [comment]
> Is there a need to make it a required extension

Only to provide users with easy access to the directive.

> have a `sphinx_immaterial.details` module (still part of this same package) that can be added by users as a separate extension

For Licensing reasons, it would be easier to not maintain an exact copy.

---
I'm still testing this dependency idea. Did you exclude merging any changes to _src/assets/stylesheets/main/extensions/pymdownx/\_details.scss_ in #34 ?

**Comment by 2bndy5** [comment]
Clearly, letting users rely on sphinx-design ext has some CSS conflicts now.

**Comment by jbms** [comment]
To be clear, I meant that the `sphinx_immaterial.details` module could still depend on the external sphinxontrib.details.directive package --- if that is what makes sense to you.

I don't believe I did anything special regarding `src/assets/stylesheets/main/extensions/pymdownx/_details.scss` in #34, so any changes should have been merged in, even though the file itself is presently excluded from the bundle --- did you notice something that was merged incorrectly?

**Comment by 2bndy5** [comment]
> did you notice something that was merged incorrectly?

It was my bad. Locally, I removed all the CSS styling for details & summarey elements in _admonitions.scss as an attempt to see how to continue support for sphinx-design (didn't entirely work out). I had to alter so many lines that I'm going with the dependency approach instead.

**Comment by 2bndy5** [comment]
It seems the class option isn't respected by the `sphinxcontrib.details.directive`
![image](https://user-images.githubusercontent.com/14963867/158483921-71145cf6-2462-4f9f-9770-166acbe05e42.png)

We may end up having to distribute a modified copy of the extension.

**Comment by 2bndy5** [comment]
Pending response from https://github.com/tk0miya/sphinxcontrib-details-directive/issues/4 about a 1 line fix which will render as expected:
![image](https://user-images.githubusercontent.com/14963867/158489477-4b9c0710-bec3-46f4-884f-3bde1c73d4a4.png)

**Comment by 2bndy5** [comment]
>To be clear, I meant that the `sphinx_immaterial.details` module could still depend on the external `sphinxontrib.details.directive` package --- if that is what makes sense to you.

We could do it that way, no objections. Since the details/summary support in mkdocs-material theme is optional I only have 1 concern about making the directive optional: The feature can only be **properly** supported by the `sphinxontrib.details.directive` package. If a user gets "clever" and uses the sphinx-design ext, then we'll be referring to this issue when they report CSS conflicts.
