### ISSUE TITLE
Navigation tabs

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#16]
Hey guys, really love what you've done here! I'm working to port over my open source project to this theme.

I know it's new and still being developed / polished. I was wondering if the [navigation tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs) feature from Material for Mkdocs is possible here with Sphinx?

**Comment by jbms** [comment]
Yes, I believe that works, you just need to enable the feature in your configuration.

**Comment by 2bndy5** [comment]
I can confirm it works. The effect is only observed on large viewports (maximized PC browsers).

Configuring the features in this theme is a little different from mkdocs-material. Please refer to [the theme's doc about customization](https://jbms.github.io/sphinx-immaterial/customization.html#features). An [example conf.py sippet](https://jbms.github.io/sphinx-immaterial) is present on the theme's landing page.

Feel free to close this if I answered your question in full.

**Comment by mhostetter** [comment]
Thank you both for the answer. I was able to "enable" the feature as described. However, I am having some difficulty understanding how to structure the files / TOC. Should each navigation tab heading be its own .rst file or its own folder of .rst files? And how do I indicate which headings go in the left-side TOC vs the right-side TOC?

Sorry for the delayed response -- I was trying to work this out myself by trial and error but didn't come to a complete solution.

**Comment by 2bndy5** [comment]
Secondary toc is just for the currently rendered rst. As for the primary toc, you can think of each collapsed item as a rendered rst. Remember each rst file can have is own `.. toctree::` structure. Examples:
```rst

.. this first tree will be collapsed into 1 entry called "API reference"; it contains 2 subitems

.. toctree::
    :caption: API reference

    classes
    modules

.. this second tree is a single rst file.
    Instead of using a caption to compress the entries,
    the rst file's first top-level heading is used as the entry's name.

.. toctree::

    related_pages
```
Note if I were to have another `.. toctree::` in my rst file named "related_pages", then those toc entries will be a sub-menu.

It just takes some playing around with.

**Comment by mhostetter** [comment]
Thanks for the response. I'll play with it some more. If I still have similar issues, I'll post back here. Or I'll open a new issue if I find a new problem. I appreciate the help and the work from both of you on this great theme!
