### ISSUE TITLE
back-links in viewcode should float right?

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#169]
I've been noticing that the links in the literal blocks generated by the viewcode ext are oddly placed at the beginning of the line with the xref'd signature. For example:
![image](https://user-images.githubusercontent.com/14963867/194731532-1ab38166-832f-4bcc-a0d9-2ceec5bd9ff0.png)
leads to
![image](https://user-images.githubusercontent.com/14963867/194731548-7d97d437-07ee-4f56-a056-da46ca7207d4.png)

Most other themes float the `[docs]` link to the right in a non-obstructive way, so I've been using custom CSS do achieve this:
```css
.viewcode-block .viewcode-back {
  float: right;
}
```
which results in
![image](https://user-images.githubusercontent.com/14963867/194731586-f63898a2-d351-408a-9656-56a4fc704f22.png)

I was wondering if the CSS I'm using should be added to this theme's CSS.

**Comment by jbms** [comment]
Yeah that sounds like a good idea.

**Comment by 2bndy5** [comment]
FYI, I also intend to do a merge from upstream soon (which should help resolve #61)

**Comment by jbms** [comment]
> FYI, I also intend to do a merge from upstream soon (which should help resolve #61)

That would be great!
