### ISSUE TITLE
can't render docs with built/installed theme on windows

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#18]
I keep running into a problem when using `npm` on windows to build the theme. It installs fine, but any docs built from the install doesn't properly link to the correct names of compiled CSS files in the installed theme's base.html template.

The generated docs try linking to files named _main.css_ and _pallete.css_. However, they should be named _main.\<sha>.min.css_ and _pallete.\<sha>.min.css_. I suspect it has something to do with the [_tools/build_](https://github.com/jbms/sphinx-immaterial/tree/main/tools/build) JS module.

Looking for JS advice again...
```
(venv) PS C:\path\to\sphinx-immaterial> npm -v
8.1.2
```

-----------
I have resorted to using WSL ubuntu bash (& related npm v8.1.2) to build a wheel and install to a Windows venv. Note that sphinx (& python in general) runs faster in Windows PS than it does in WSL terminal for some reason.

**Comment by 2bndy5** [comment]
I realize now (after learning more about npm) that solving this may be dependent on upstream's dev workflow. Closing this.

**Comment by jbms** [comment]
Sorry, I missed this issue when you posted it previously.  There is some logic in the build scripts copied (with some modifications) from mkdocs-material that handles renaming of the files, and it should be possible to fix this.  If there is a bug in the upstream repository it could be fixed there as well.
