### ISSUE TITLE
Search does not jump to precise Python object and only jumps to top of page.

### ISSUE THREAD

**Issue by jgarte** [jbms/sphinx-immaterial#198]
Hi,

When I search on this sphinx-immaterial website and choose a Python object it always takes me to the top of the page instead of directly to the Python object that I'm searching for:

https://josiahwolfoberholtzer.com/uqbar/

For example,

If I search for the query `add`:

![image](https://user-images.githubusercontent.com/47760695/210476220-8ad27c7e-5a59-4baf-bed1-4726b80ab76a.png)

When I get redirected it takes me to the top of the page and to this url:

https://josiahwolfoberholtzer.com/uqbar/api/uqbar/containers/dependency_graph.html#

![image](https://user-images.githubusercontent.com/47760695/210476582-e0b216e0-2e9b-45e3-b586-3a15b2903c69.png)

What `sphinx-immaterial` needs to do is redirect to this url instead:

https://josiahwolfoberholtzer.com/uqbar/api/uqbar/containers/dependency_graph.html#uqbar.containers.dependency_graph.DependencyGraph.add

So that I can arrive here:

![image](https://user-images.githubusercontent.com/47760695/210476452-4801323b-fee9-459e-b651-0d7ff0ffb24c.png)

This issue also happens on a local project.

Is this a bug or am I missing some feature that needs to be enabled?

**Comment by 2bndy5** [comment]
fix released with v0.11.2
