### ISSUE TITLE
Sphinx 4.3 Compatability

### ISSUE THREAD

**Issue by SimonBoothroyd** [jbms/sphinx-immaterial#21]
Firstly, thanks for making this port available - it works and looks amazing!

It seems the newest version of sphinx (4.3) has a few API changes that leads to some breaks in this package. Namely:

* `sphinx.search.IndexBuilder.get_objects()` now returns a list of tuples rather than a dict, where the old dict key has now been included as the last item in the tuple.
* `get_signature_prefix` now returns a list of nodes rather than strings.

I'd be happy to contribute a PR with possible fixes if you'd like.

**Comment by 2bndy5** [comment]
A PR is indeed welcome. May I suggest you keep backwards compatibility (at least with sphinx v4.x) by using the `sphinx.version_info` tuple?

**Comment by jbms** [comment]
It turns out that #22 did not fully fix 4.3 compatibility.  Because of the change in the search index format, the JavaScript code also needs to be updated.

I'm working on that fix, but I'm inclined to just require Sphinx 4.3, because trying to support 2 search index formats is a fair bit of trouble.

Is support for Sphinx < 4.3 important?

**Comment by 2bndy5** [comment]
Currently, it is the version that gets installed from pip. Unless, you change the `install-requires` value in _setup.py_ (& _requirements.txt_).

My only concern about pinning to the latest release of sphinx (which clearly broke some compatibility) is that this requirement might conflict with other extensions that haven't conformed (yet).

**Comment by jbms** [comment]
This theme depends on sphinx internals a lot more than most themes, I suspect.

I would like to see most of the changes ultimately upstreamed in sphinx itself as that would make them more maintainable, and more widely usable, but that will take some time.

**Comment by jbms** [comment]
It turned out to not be too difficult to retain compatibility with Sphinx 4.2 after all.
