### ISSUE TITLE
"language" parameter missing in docs, build fails when there's none in conf.py

### ISSUE THREAD

**Issue by Vegebutcher** [jbms/sphinx-immaterial#23]
Hi,
Recently I stumbled upon your project while looking for a Sphinx theme that would make our Python API docs (hosted on RTD) similarly looking to the general docs built in Material for MkDocs. A bit disappointed with the sphinx-material theme, I decided to test yours. Unfortunately, my first build attempts were unsuccessful:

`writing output... [ 20%] galaxy.api
Theme error:
An error happened in rendering the page galaxy.api.
Reason: TemplateNotFound('partials/languages/None.html')`

I figured out it sth related to the language of the project, but in your docs there's nothing about the need to set the language in the `conf.py` file, otherwise the builder will fail (I guess it takes the `None` value and looks for the respective `None.html` file, which simply doesn't exist). In your `conf.py` file I found `language = "en"`, put it into my `conf.py` and it worked like a charm.

You should either update the docs with some info regarding this parameter or implement an exception, which handles unspecified language by defaulting to EN, for instance.

Apart from that, it's a fantastic work! I'm impressed how smoothly you integrated the great Material for MkDocs theme with Sphinx.

**Comment by 2bndy5** [comment]
+1 to this. I've run across this as well when testing the theme with my breathe contributions. 

This should be easy enough to solve by adding a default value (likely `"en"`) to the dict of default config options.

https://github.com/jbms/sphinx-immaterial/blob/191bc367888e3834db0d6f6f6ce82a2bcce0d903/sphinx_immaterial/__init__.py#L26-L38

add 
```py
    "language": "en",
```
