### ISSUE TITLE
Search missing most content

### ISSUE THREAD

**Issue by vsoch** [jbms/sphinx-immaterial#235]
Hiya! I'm using your theme at https://flux-framework.org/flux-operator (love it!) and I've noticed that the search isn't showing most of the content (e.g., browse the site, find a term, search for it, no results?)

This might not be related to your theme but using markdown for the source files - as an example for another related project https://flux-framework.readthedocs.io/en/latest/ we use .rst and the search seems well populated.

Have you seen this bug before and do you know if there is a  fix or workaround for it? Or do you know the right place I might ask? Thank you! 

- Related issue https://github.com/flux-framework/flux-operator/issues/96

**Comment by jbms** [comment]
It sounds like this issue:

https://github.com/sphinx-doc/sphinx/pull/11192

I don't think there is currently a released version with this fix so you will need to use an older version of Sphinx.

**Comment by vsoch** [comment]
Gotcha - I’ll test this out and post an update (and close after that). Thanks for the quick response and your expertise! 🙏

**Comment by vsoch** [comment]
Worked like a charm! For anyone that stumbles on this issue, the fix was just to install from the sphinx master (temporary) until the change is released. E.g., in my docs build for GitHub pages:

```bash
# Install sphinx from master for this bug:
# https://github.com/sphinx-doc/sphinx/pull/11192
git clone --depth 1 https://github.com/sphinx-doc/sphinx /tmp/sphinx
cd /tmp/sphinx
pip install .
cd -
```
And then install your other deps (sphinx will be found) and build the docs, push to gh-pages, working again!

![image](https://user-images.githubusercontent.com/814322/224570150-6640c0d7-0745-4006-b181-5cc4cab5eecd.png)

Thanks so much @jbms - I would never have stumbled on this fix.
