### ISSUE TITLE
`font` instead of `fonts` in docs

### ISSUE THREAD

**Issue by Vegebutcher** [jbms/sphinx-immaterial#28]
Found another bug in the theme docs: in the _[New blocks](https://jbms.github.io/sphinx-immaterial/customization.html#new-blocks)_ section there's a description of a block responsible for substituting the default font. But it should read `fonts` instead of `font` – I realised that only after reading the code of the default `layout.html` file here in the repo:

<img width="706" alt="font instead of fonts" src="https://user-images.githubusercontent.com/907743/143959075-56289194-5757-4498-a8f6-f9d48472f4bd.png">

When you use the following `font` block in the /_template/layout.html file that overrides defaults, nothing happens (the text font is still Roboto):

```jinja
{# Import the theme's layout. #}
{% extends '!layout.html' %}

{% block font %}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700%7CRoboto+Mono&display=fallback"
        />
        <style>
          :root {
            --md-text-font-family: "Lato";
            --md-code-font-family: "Roboto Mono";
          }
        </style>
{% endblock %}
```

But this code works when you use `{% block fonts %}`.

**Comment by jbms** [comment]
You can actually change the fonts without overriding templates at all, just using:

```python
"font": {"text": "Roboto", "code": "Roboto Mono"},
```

in your `html_theme_options`.

We should adapt the documentation based on this:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/

**Comment by 2bndy5** [comment]
Also I'm pretty sure `fonticon` won't work here.

**Comment by Vegebutcher** [comment]
The trick with `font` in `html_theme_options` indeed works, thanks!

Didn't check `fonticon` at all, so can't tell.

**Comment by 2bndy5** [comment]
I don't see anything in the templates that makes use of a `fonticon` block. I think this is a relic from sphinx-material theme's docs.

On the other hand, `footerrel` seems to have been inherited from the mkdocs-material upstream. See footer.html template
