### ISSUE TITLE
the theme does not detect the repo if there is no final "/"

### ISSUE THREAD

**Issue by 12rambau** [jbms/sphinx-immaterial#287]
I was setting the "repo-url" option to the URL of my github repository: "https://github.com/12rambau/pytest-copie" and without a final "/" the theme was not able to detect it was a GitHub repository (disabling release and stars features).

Is it a wanted behaviour ?

**Comment by 2bndy5** [comment]
Obviously that's not wanted behavior. Should be an easy fix though. Can I see what the error says? I have a hunch.

**Comment by 12rambau** [comment]
there are no errors I simply get the display corresponding to a non-github repo with the Git icon

**Comment by 2bndy5** [comment]
Is this local only? I can't reproduce this. I had suspected something like:
https://github.com/jbms/sphinx-immaterial/blob/5756b7fabfde981e27a0cc1a3e9459bc897e9d7b/sphinx_immaterial/__init__.py#L270-L282
You don't see anything in the build log or web console?

**Comment by 2bndy5** [comment]
This is the JS side of it:
https://github.com/jbms/sphinx-immaterial/blob/5756b7fabfde981e27a0cc1a3e9459bc897e9d7b/src/assets/javascripts/components/source/facts/_/index.ts#L71-L88
where the REST API is probed with:
https://github.com/jbms/sphinx-immaterial/blob/5756b7fabfde981e27a0cc1a3e9459bc897e9d7b/src/assets/javascripts/components/source/facts/github/index.ts#L64-L88
I'm not seeing anything that would be a problem.

Was this a problem in upstream mkdocs-material? We are currently pinned to v8.5.6 or something.

**Comment by 12rambau** [comment]
I was 100% sure to have check multiple time before opening the issue. I cannot reproduce it anymore. I guess I was missing another parameter.... 

Sorry for the noise. I should have worked and it did....
