### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by naor2013** [jbms/sphinx-immaterial#30]
We have a weird error when we try to build our docs.
In most of our computers it works, in some it doesn't, I can't put my fingers on what is different between them.
Same Sphinx version (4.2.0), same Sphinx-immaterial version (0.2.0), similar Python version (3.7+), same code.

The error is:
Extension error (sphinx_immaterial.object_toc):
Handle <bound method _monkey_patch_toc_tree_process_doc.<locals>._patched_process_doc of <sphinx.environment.collectors.toctree.TocTreeCollector object at {id}>> for event 'doctree-read' threw an exception (exception: 'desc' object has no attribute '_traverse')

Thanks :)

**Comment by jbms** [comment]
You can debug by specifying the `-P` option to `sphinx-build`.  That will bring you to a pdb shell when the error occurs which will hopefully allow you to better determine the cause.

If you still can't figure it out, if you are able to provide me with a way to reproduce, e.g. in a docker container, I can take a look.

**Comment by 2bndy5** [comment]
Usually when sphinx-immaterial throws an error like this, there is a log file (typically stored in the OS's temp folder) containing the full traceback message. This is usually helpful to me when I need to figure out where to start looking in sphinx-immaterial sources.

**Comment by 2bndy5** [comment]
@naor2013 On a second look, I'm guessing that some other sphinx-extension is incompatible with the `sphinx_immaterial` extension (included with the theme). I'd probably blame an extension that has something to do with member signatures (maybe `sphinx.ext.inheritance_diagram` or `sphinx_autodoc_typehints`).

If you could provide the source (or an example of the source), then we can better attempt to reproduce this and discern a course of action. However, I can only try with Windows And Ubuntu OSs; personally, I'm rather anti-apple devices.

**Comment by 2bndy5** [comment]
Alomst a year and no response, reproduction, or suggested possible solution... closing this. Please re-open and submit more detail if this is still a problem.
