### ISSUE TITLE
`"navigation.tabs"` links to page's first section

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#31]
I'm in the process of converting my library over to this theme. Thanks for all the hard work creating this fork!!

I noticed when using navigation tabs that after clicking on the tab, the page `/the-page.html` is loaded with `#first-section` appended. So the URL is `/the-page.html#first-section` and not `/the-page.html`.

This can be observed on @2bndy5's website https://circuitpython-nrf24l01.readthedocs.io/en/latest/index.html.

![image](https://user-images.githubusercontent.com/12112573/154067998-cdb5b360-d566-45c9-b9a2-b140d230a1de.png)

When clicking "Network API Reference", the URL `/topology.html#network-levels` is loaded and not `/topology.html`.

![image](https://user-images.githubusercontent.com/12112573/154068121-fefaa736-d095-48eb-95ba-415b4cc2e9ca.png)

Desired output:

![image](https://user-images.githubusercontent.com/12112573/154068440-00063c51-6444-4858-a7d5-3717841c648e.png)

PS: I noticed that when clicking on a navigation tab while currently on that tab (but halfway down the page), it loads the page correctly without the `#first-section` appended.

**Comment by 2bndy5** [comment]
> I noticed when using navigation tabs that after clicking on the tab, the page /the-page.html is loaded with #first-section appended. So the URL is /the-page.html#first-section and not /the-page.html.

I also noticed that a while back, but I didn't think anything of it. Apparently, your desired behavior is consistent with mkdocs-material theme.

>PS: I noticed that when clicking on a navigation tab while currently on that tab (but halfway down the page), it loads the page correctly without the #first-section appended.

You shouldn't be able to see the tabs (let alone click on them) if you've scrolled down at all. I can't reproduce this bit.

**Comment by mhostetter** [comment]
> You shouldn't be able to see the tabs (let alone click on them) if you've scrolled down at all. I can't reproduce this bit.

You're right. I had to scroll back to the top and then click the tab. However, when doing so once already on the tab, it didn't link to the `#first-section` like it does when clicking a tab from a different page entirely.

**Comment by mhostetter** [comment]
This may help in the debugging...

When clicking the "Troubleshooting Info" tab on https://circuitpython-nrf24l01.readthedocs.io/en/latest/index.html, it links to "Attribute dependency" which is a 3rd-level heading. It is also the last heading before normal paragraph text is inserted. Maybe that is related to which section is linked?

**Comment by 2bndy5** [comment]
Looking at the source for that site, it seems as though the tabs are directing to the sections that use `*****` as a header's underscore.
```rst
Network Topology
================

Network Levels
****************
```
and 
```rst

Troubleshooting info
~~~~~~~~~~~~~~~~~~~~

Common Problems
===============

Attribute dependency
********************
```
I'm not sure if my CirPy_nRF24 docs are a good example of section ordering because I had to dirty-hack all the pages so they didn't use multiple root-level headers. @mhostetter Is this reported behavior consistent with the site you're putting together?

**Comment by 2bndy5** [comment]
I take that comment about the header syntax back. Clicking on the "Examples" tab directs to `examples.html#simple-test`, and that header does not use the same underscore symmbol
```rst
Examples
~~~~~~~~~~~~

nRF24L01 Features
=================

Simple test
------------
```

@mhostetter You may be on to something with the first section that has a body implication.

**Comment by mhostetter** [comment]
@2bndy5 well maybe not so fast... Looking at my cases, my pages look like this:

```
Title
=====

Paragraph of text.

Section 1
---------

More paragraphs.
```

and in each case "Section 1" is linked.

I just tested this:

```
Title
=====

Paragraph of text.

Section 1
---------

More paragraphs.

Section 2
^^^^^^^^^

Even more paragraphs.
```

which results in "Section 2" being linked.

As an aside, rST heading markup is **crazy** and impossible to determine heading level. Markdown's simple `#`, `##`, `###`, ... is so much easier. *sigh*

**Comment by 2bndy5** [comment]
> As an aside, rST heading markup is crazy and impossible to determine heading level. Markdown's simple #, ##, ###, ... is so much easier. sigh

Understandable. FWIW, sphinx (or docutils) usually outputs an error when headings don't follow a uniform order.
```rst
H1-1
====
H2-1
----
H1-2
====
H2-2
****
Boom! H2-2 should use ``----`` because H2-1 does
```

---
I'll have to start digging into the source code. This doesn't seem to be effected by other features (like `navigation.instant`).

**Comment by 2bndy5** [comment]
@mhostetter It would help to have a link to the docs' src that you're working on.

**Comment by mhostetter** [comment]
If it is helpful, I could try to push something up that is clone-able and buildable. Although, that would add all the complexity of my library to this debugging effort.

I referenced your website because I knew you were a developer here and thought that might be the easiest reproducer.

If it would be helpful, let me know and I can do it.

**Comment by 2bndy5** [comment]
Yeah, my docs' site you referenced in the OP isn't the most sphinx-immaterial compliant docs. They were ported from sphinx-rtd-theme -> then ported to sphinx-material theme -> then ported to sphinx-immaterial theme.

**Comment by 2bndy5** [comment]
And here I was just focusing on [tab-item.html template](https://github.com/jbms/sphinx-immaterial/blob/main/src/partials/tabs-item.html). I feel a bit out of touch with this repo's src.

**Comment by mhostetter** [comment]
@2bndy5 here is my project and branch https://github.com/mhostetter/galois/tree/port-to-sphinx-immaterial.

Clone the repo:

```
$ git clone https://github.com/mhostetter/galois.git@port-to-sphinx-immaterial
```

Install the doc dependencies:

```
$ cd galois/
$ python3 -m pip install -r docs/requirements.txt
```

Build the docs:

```
$ sphinx-build -b html -v docs/ docs/build/
```

One example is the "Getting Started" page which links to the first section "Install the package".

![image](https://user-images.githubusercontent.com/12112573/154089195-971902f6-c6df-4f22-ac88-ddad1f9ec264.png)

**Comment by 2bndy5** [comment]
@mhostetter Just on first glance (seems unrelated to this issue though):
https://github.com/mhostetter/galois/blob/48e2fe63047307bc126cb4be0a315ad0a67aedff/docs/conf.py#L111

[`navigation.indexes`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) is a feature specific to mkdocs-material v7.3.0. this theme is based on v7.2.2

**Comment by mhostetter** [comment]
This may help in the debugging...

I noticed that on mobile clicking on a navigation tab does *not* jump to a section or subsection. This can be reproduced on desktop by zooming enough so that the navigation bar moves into the "hamburger".

For instance, with my docs on https://galois.readthedocs.io/en/latest/index.html.

![image](https://user-images.githubusercontent.com/12112573/155231903-9d84bc4b-92f8-42e7-b625-56efc53d5c42.png)

Clicking on the "Basic Usage" navigation tab loads this subsection, not the top of the page.

![image](https://user-images.githubusercontent.com/12112573/155232200-2063199f-9a64-4484-a544-d544d1c40218.png)

However, zooming enough so the homepage looks like this

![image](https://user-images.githubusercontent.com/12112573/155232071-017ceb05-fd24-4fd3-8167-01b9779043b0.png)

and then selecting "Basic Usage" from the hamburger, results in loading the top of the page, which is the desired usage.

![image](https://user-images.githubusercontent.com/12112573/155232132-e8a1e060-25d4-4dbf-8665-993f254cb768.png)

Does this indicate the issue lies solely in `tab-item.html`?

**Comment by jbms** [comment]
I think the issue lies in the interaction between `tabs-item.html` and `nav_adapt.py`.

mkdocs has a different table-of-contents model from sphinx, and here we are running into a minor conflict.

I think the intent of `tabs-item.html` is to find the first descendant that is actually a linkable page, rather than purely a toc heading.  So it would probably be simplest to just modify `tab-items.html`, even though in general it is best to minimize changes to the mkdocs-material html templates in order to minimize the chance of merge conflicts when pulling in upstream changes later.

**Comment by 2bndy5** [comment]
> even though in general it is best to minimize changes to the mkdocs-material html templates

If I understand, this correctly, we would need to add a separate template context var for tabs (call it `tab_items`), right? I got lost trying to track how the `nav_items` differ between _nav-item.html_ and _tab-item.html_.

**Comment by jbms** [comment]
Yeah we could try to do most of the work in nav_adapt.py but it would still require a small change to tabs-item.html.  I think the simpler fix in this case is to just modify tabs-item.html --- instead of checking for `children`, check for `not nav_item.url`.

**Comment by 2bndy5** [comment]
Agreed.

I also noticed that a tab item in which the toc entry is just RST links will forward to only the first link in the list. This is exemplified in my CirPy_nRF24 docs' "other links" tab.
[![image](https://user-images.githubusercontent.com/14963867/155248775-3c6f921c-6f11-4736-84a2-a9ee8c70bd49.png)](https://circuitpython-nrf24l01.readthedocs.io/en/latest/index.html)
<details><summary>rst src code</summary>

```rst
.. toctree::
    :caption: Other Links
    :hidden:

    Download <https://github.com/2bndy5/CircuitPython_nRF24L01/releases/latest>
    CircuitPython Reference Documentation <https://circuitpython.readthedocs.io>
    CircuitPython Support Forum <https://forums.adafruit.com/viewforum.php?f=60>
    Discord Chat <https://adafru.it/discord>
    Adafruit Learning System <https://learn.adafruit.com>
    Adafruit Blog <https://blog.adafruit.com>
    Adafruit Store <https://www.adafruit.com>
```
</details>

We should probably put a note in the docs that this convention cannot be supported with navigation tabs. Although it is supported in the side navigation menu.
![image](https://user-images.githubusercontent.com/14963867/155248868-45f115f5-49e7-43ab-b877-5e079125f92b.png)

**Comment by jbms** [comment]
Regarding the link just forwarding to the first item --- that is also how mkdocs-material works (actually I think it is worse in mkdocs because mkdocs does not allow a toc entry with children to itself be a page).  It would indeed be worthwhile mentioning that when using the `navigation.tabs` feature it is best to make sure each top-level entry is itself a page.

**Comment by mhostetter** [comment]
@jbms I'm trying to understand what you mean...

Previously, following @2bndy5's example with his project, at the bottom of my `index.rst` file I had:

```
# index.rst

Homepage stuff...

# Tab 1 has only one page
.. toctree::
   :caption: Tab 1
   :hidden:

   tab-1.rst 

# Tab 2 has three pages
.. toctree::
   :caption: Tab 2
   :hidden:

   tab-2/page-1.rst
   tab-2/page-2.rst
   tab-2/page-3.rst
```

Are you suggesting it should instead be structured like this? Where each entry in the toctree of `index.rst` is its own page?

```
# index.rst

.. toctree::
   :hidden:

   tab-1.rst
   tab-2.rst
```

```
# tab-2.rst
Tab 2
=====

.. toctree::
   :hidden:

   tab-2/page-1.rst
   tab-2/page-2.rst
   tab-2/page-3.rst
```

I'm testing this currently with my project, but am seeing identical behavior.

**Comment by jbms** [comment]
To be clear, a fix to tabs-item.html is still needed, but the change in toc structure is needed in order for the tab to be able to link to tab-2 rather than page1.  Even if you don't change the toc structure, with tabs-item.html fixed, the original issue would be resolved --- it would link to a page rather than a sub-section.

**Comment by mhostetter** [comment]
> To be clear, a fix to tabs-item.html is still needed, but the change in toc structure is needed in order for the tab to be able to link to tab-2 rather than page1.

I see. I actually desire when clicking on "Tab 1" for `tab-1/page-1.rst` to load first.

I found the minor change in #32 resolves my issues.
