### ISSUE TITLE
"Copy to clipboard" and "Back to top" Buttons Disappear After Adjusting Theme Settings

### ISSUE THREAD

**Issue by urvantsev** [jbms/sphinx-immaterial#336]
My goal was to adjust the "palette" settings to use the dark theme exclusively by removing the toggle option. However, after making this adjustment, I've noticed that the "Copy to clipboard" buttons within code blocks and the "Back to top" buttons have disappeared. I don't see any obvious connection between the "palette" adjustments and these buttons, leading me to suspect this may be a bug.

![image](https://github.com/jbms/sphinx-immaterial/assets/37312170/f0452212-027f-4507-a3e0-316f25c24a0d)

On the left, the "palette" was edited to enable only the Dark theme, resulting in the unintended side effect of the "Copy to clipboard" and "Back to top" buttons disappearing. On the right is the "palette" after reverting this change, after that the "Copy to clipboard" and "Back to top" buttons reappeared as expected.

**Comment by 2bndy5** [comment]
Did you try doing a fresh rebuild (`sphinx-build -a`) after making the edits?

**Comment by urvantsev** [comment]
@2bndy5, yes, I've been playing with this quite some time, tried to rebuild from fresh multiple times on different machines (locally and on the server where we host it), same behavior.

**Comment by 2bndy5** [comment]
I still think there's something you have overlooked. I cannot reproduce using this theme's docs and the changes demonstrated in the OP.

> "Copy to clipboard" and "Back to top" buttons

Both of these buttons are implemented in JS, so it could just be the browser you are using.

**Comment by urvantsev** [comment]
@2bndy5, I confirm that it is browser related. It works in Edge, but doesn't work in Chrome, for example.

**Comment by 2bndy5** [comment]
Still a bit odd. I think most people use Chrome; I use firefox and boycott edge.
Since it is JS at fault here, then one of the extensions you enabled in chrome might be preventing the theme's JS to start properly. Best to press F12 and check the console for error messages.

**Comment by urvantsev** [comment]
@2bndy5, error message:

![image](https://github.com/jbms/sphinx-immaterial/assets/37312170/5667c55a-eecb-4911-b86a-13da59b53732)

**Comment by 2bndy5** [comment]
Sorry you have to figure that out yourself. At least you have something to start with. My guess is that some browser extension is altering the site's DOM before the theme JS is done loading.

Maybe go through your chrome extensions and disable them one at a time to see if the error goes away. I can't do much for you since the theme works fine in my local install of chrome.

> [!NOTE]
> Enabling [`sphinx_immaterial_bundle_source_maps`](https://jbms.github.io/sphinx-immaterial/customization.html#confval-sphinx_immaterial_bundle_source_maps) should help make the error message more readasble.

**Comment by ahill187** [comment]
I'm having the same issue, and it isn't browser-specific (it fails on both Safari and Chrome)...

**Comment by 2bndy5** [comment]
Is it the _exact_ same problem? Or is it just similar? We can't help you unless you give us details.

This problem wasn't specific to a browser, rather it was caused by some browser extension. Try incognito mode or start removing browser extensions that might be altering the page's DOM.
