### ISSUE TITLE
`sphinx_immaterial_custom_admonitions` not applying `classes` by default

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#352]
Hello, again. Thanks for all the hard work on this great theme!

I made a custom admonition like so. I assumed that `"classes": ["collapsible"],` would automatically make it collapsible (and collapsed).

```python
sphinx_immaterial_custom_admonitions = [
    {
        "name": "nomenclature",
        "title": "Variable nomenclature",
        "classes": ["collapsible"],
        "icon": "fontawesome/solid/arrow-down-a-z",
        "color": (108, 117, 125),  # --sd-color-secondary
    },
]
```

However, when I instantiate the admonition like so, I get the following result.

```rst
    .. nomenclature::

        - $k$: Symbol index
```

![image](https://github.com/jbms/sphinx-immaterial/assets/12112573/f3fda125-a80f-40eb-ba5a-401abf8b898b)

If I explicitly add `:collapsible:`, then it works.

```rst
    .. nomenclature::
        :collapsible:

        - $k$: Symbol index
```

![image](https://github.com/jbms/sphinx-immaterial/assets/12112573/57f48cf0-db2b-48d3-94bf-f950b5be1843)

Is this the desired effect? Thanks, as always.

**Comment by 2bndy5** [comment]
> Is this the desired effect?

Yes. The [`:collapsible:` directive option](https://jbms.github.io/sphinx-immaterial/admonitions.html#directive-option-admonition-collapsible) does not have anything to do with CSS classes. If you define a custom CSS [`classes` in the config](https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.classes), then you should also define the style rule(s) in CSS that should be applied. Note: the `classes` config option is a convenience to augment the default value used by the [`:class:` directive option](https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.classes).

**Comment by 2bndy5** [comment]
FWIW, I'm not excited by the suggestion that the `collapsible` should/could be defined at the config level. Implementing such a "feature" might be too brittle to maintain, given the multitude of supported/overridden admonition and version directives.

**Comment by mhostetter** [comment]
Ok, thanks. I confused directive options and CSS classes. I'll add the directive option to the places I want to use it. Thanks.
