### ISSUE TITLE
Typo in index.rst

### ISSUE THREAD

**Issue by 91Seconds** [jbms/sphinx-immaterial#354]
Hey, I love the project.  

I was following the main page of the [read the docs site](https://jbms.github.io/sphinx-immaterial/) and getting a lot of errors.  I eventually found out that if I changed [line 69 of index.rst](https://github.com/jbms/sphinx-immaterial/blob/a23535f/docs/index.rst?plain=1#L69) from `extension = ["sphinx_immaterial"]` to `extensions = ["sphinx_immaterial"]` it worked fine.  

I believe that line should read `extensions = ["sphinx_immaterial"]`

**Comment by 2bndy5** [comment]
You are correct. You want to submit a PR?
