### ISSUE TITLE
numpydoc type specification breaks formatting

### ISSUE THREAD

**Issue by till-m** [jbms/sphinx-immaterial#375]
When specifying the type of a function parameter in the signature, adding a space before the colon breaks the formatting, removing both the colon and the spaces around it. This space is mandatory according to the [numpydoc guide](https://numpydoc.readthedocs.io/en/latest/format.html#parameters).

![image](https://github.com/user-attachments/assets/fe26e2c0-99c1-4cfe-abd3-ec3a4c2739ab)
![image](https://github.com/user-attachments/assets/66ad8e23-46e2-458d-bc87-2bd6cc1c4b36)

**Comment by 2bndy5** [comment]
@till-m I noticed that your project does not use [`sphinx.ext.napoleon` extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html). Typically this is needed to properly support numpy style docstrings.
```python
# in conf.py
extensions = [
    # ...
    "sphinx_immaterial",
    "sphinx.ext.napoleon",
]
```

### Using alabaster theme
output with the extension enabled: 
![image](https://github.com/user-attachments/assets/2a52f8e2-8b1b-4ff3-8989-d258fe1a30e4)
output without the extension enabled:
![image](https://github.com/user-attachments/assets/3b7571ac-268b-42d4-9029-3db2ffb4a32d)

### Using sphinx-immaterial theme
output with the extension enabled: 
![image](https://github.com/user-attachments/assets/4f69c232-7f08-420f-bb25-c3520a06e8b3)
output without extension enabled:
![image](https://github.com/user-attachments/assets/b9d68bf8-5b68-421d-9503-785f7a72a04b)

**Comment by 2bndy5** [comment]
I created a sample project to reproduce: [test-sample.zip](https://github.com/user-attachments/files/16401615/test-sample.zip). I used this to post the pictures in my above comment.

**Comment by till-m** [comment]
Thanks so much, apologies for missing this!

**Comment by till-m** [comment]
Hey @2bndy5,

slightly related, but it seems that the `Return` section doesn't work properly, see e.g. [here](https://bayesian-optimization.github.io/BayesianOptimization/1.5.1/reference/constraint.html#bayes_opt.constraint.ConstraintModel.approx).
![Screenshot 2024-09-08 at 13 31 42](https://github.com/user-attachments/assets/c2f1fae4-2597-4a86-bfad-bbabc35944b9)

Would you happen to know how to fix that?

**Comment by 2bndy5** [comment]
I haven't looked into it. In general the Napoleon extension is really just translating the docs strings into RST syntax. In RST syntax you can document the return type using the `rtype` field.

```rst
:returns: Some data's meaning/behavior.
:rtype: int
```

So if Napoleon extension fails to parse the return type from your doc string, you might need to raise an issue with sphinx itself (because that's where the Napoleon extension is developed). Given that this is your doc string in question:

```
        Returns
        -------
        np.ndarray of shape (n_samples,)
            Probability of constraint fulfilment.
```
Personally, I don't think that `np.ndarray of shape (n_samples,)` is an actual type. Rather, that seems more like a description of a type; an actual type does not have spaces in its name.

I would suspect that it might parse better if the return type was something more like: 
```
        Returns
        -------
        np.ndarray[n_samples]
            Probability of constraint fulfilment (of a shape).
```

**Comment by till-m** [comment]
Hey @2bndy5,

thanks for putting so much effort in for me! I wrote some `rst`-style docstrings as a test and this is the best result I got:
<img width="679" alt="Screenshot" src="https://github.com/user-attachments/assets/818104ef-4804-4a61-9405-8b7d8531a45e">


Just to check -- is this how the returns should "ideally" look?

**Comment by 2bndy5** [comment]
Yep. That's what I'm accustomed to seeing. 

> [!tip]
> See also the Napoleon extension's [`napoleon_use_rtype` config option](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#confval-napoleon_use_rtype) documentation.
