### ISSUE TITLE
Monospace code with box characters

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#38]
I noticed that [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) in `sphinx-immaterial` don't print with the same width. I tried several different fonts, even ones I know to "work" elsewhere, but can't seem to get uniform spacing. I've been digging into the CSS to try to determine what parameters could affect this (ligatures, etc). I was curious if anything in https://github.com/squidfunk/mkdocs-material/issues/323 was related. Given my very limited HTML/CSS knowledge, this has proved difficult.

Any thoughts?

## `sphinx-immaterial`

![image](https://user-images.githubusercontent.com/12112573/156223890-fbbe2dd3-0e4c-4e41-93e7-21d6d1c2e6f8.png)

## `sphinx_rtd_theme`

![image](https://user-images.githubusercontent.com/12112573/156223799-50c5ff3c-efba-4f95-81dd-00d6bf1f03b6.png)

## VS Code

![image](https://user-images.githubusercontent.com/12112573/156223687-23da1c11-5831-4dbe-87d8-9ff2ce300f92.png)

**Comment by 2bndy5** [comment]
>I tried several different fonts, even ones I know to "work" elsewhere

How do we reproduce this? What fonts did you try?

**Comment by mhostetter** [comment]
I changed the font this way. I tried many fonts from https://fonts.google.com/, as mentioned [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/) by Material for Mkdocs.

```python
html_theme_options = {
    "font": {
        "code": "Ubuntu Mono"
    },
}
```

Sorry, I should have included a reproducer.

## Example

Place this .rst snippet in any file.

```rst
This is a test box.

.. code-block:: python

   In [15]: print(GF9.arithmetic_table("+"))
   ╔════════╦════════╤════════╤════════╤════════╤════════╤════════╤════════╤════════╤════════╗
   ║  x + y ║      0 │      1 │      2 │      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 ║
   ╠════════╬════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╣
   ║      0 ║      0 │      1 │      2 │      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║      1 ║      1 │      2 │      0 │  α + 1 │  α + 2 │      α │ 2α + 1 │ 2α + 2 │     2α ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║      2 ║      2 │      0 │      1 │  α + 2 │      α │  α + 1 │ 2α + 2 │     2α │ 2α + 1 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║      α ║      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 │      0 │      1 │      2 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║  α + 1 ║  α + 1 │  α + 2 │      α │ 2α + 1 │ 2α + 2 │     2α │      1 │      2 │      0 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║  α + 2 ║  α + 2 │      α │  α + 1 │ 2α + 2 │     2α │ 2α + 1 │      2 │      0 │      1 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║     2α ║     2α │ 2α + 1 │ 2α + 2 │      0 │      1 │      2 │      α │  α + 1 │  α + 2 ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║ 2α + 1 ║ 2α + 1 │ 2α + 2 │     2α │      1 │      2 │      0 │  α + 1 │  α + 2 │      α ║
   ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
   ║ 2α + 2 ║ 2α + 2 │     2α │ 2α + 1 │      2 │      0 │      1 │  α + 2 │      α │  α + 1 ║
   ╚════════╩════════╧════════╧════════╧════════╧════════╧════════╧════════╧════════╧════════╝
```

## Output

![image](https://user-images.githubusercontent.com/12112573/156228332-c78ba951-5e6d-4144-9686-a059a09802e9.png)

## HTML Output

```html
<html>
<body>
<!--StartFragment-->

<p>This is a test box.</p>
--
  | <div class="highlight-python notranslate"><div class="highlight"><pre><span></span><code>In [15]: print(GF9.arithmetic_table(&quot;+&quot;))
  | ╔════════╦════════╤════════╤════════╤════════╤════════╤════════╤════════╤════════╤════════╗
  | ║  x + y ║      0 │      1 │      2 │      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 ║
  | ╠════════╬════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╣
  | ║      0 ║      0 │      1 │      2 │      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║      1 ║      1 │      2 │      0 │  α + 1 │  α + 2 │      α │ 2α + 1 │ 2α + 2 │     2α ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║      2 ║      2 │      0 │      1 │  α + 2 │      α │  α + 1 │ 2α + 2 │     2α │ 2α + 1 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║      α ║      α │  α + 1 │  α + 2 │     2α │ 2α + 1 │ 2α + 2 │      0 │      1 │      2 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║  α + 1 ║  α + 1 │  α + 2 │      α │ 2α + 1 │ 2α + 2 │     2α │      1 │      2 │      0 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║  α + 2 ║  α + 2 │      α │  α + 1 │ 2α + 2 │     2α │ 2α + 1 │      2 │      0 │      1 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║     2α ║     2α │ 2α + 1 │ 2α + 2 │      0 │      1 │      2 │      α │  α + 1 │  α + 2 ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║ 2α + 1 ║ 2α + 1 │ 2α + 2 │     2α │      1 │      2 │      0 │  α + 1 │  α + 2 │      α ║
  | ╟────────╫────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────┼────────╢
  | ║ 2α + 2 ║ 2α + 2 │     2α │ 2α + 1 │      2 │      0 │      1 │  α + 2 │      α │  α + 1 ║
  | ╚════════╩════════╧════════╧════════╧════════╧════════╧════════╧════════╧════════╧════════╝
  | </code></pre></div>

<!--EndFragment-->
</body>
</html>
```

**Comment by 2bndy5** [comment]
I was able to reproduce this using the default font. As soon as I added 
```py
html_theme_options = {
    "font": {"code": "Ubuntu mono"},
    # ...
}
```
<details><summary>Then I get the expected output</summary>

![image](https://user-images.githubusercontent.com/14963867/156232550-61613316-e377-4ff5-a9e3-9677811d21c8.png)

</details>

Notice the casing in the specified font name, namely "mono" vs "Mono".

**Comment by 2bndy5** [comment]
I also had to change the code-block syntax lfor language highlighting because 
```rst
.. code-block:: python
```
will produce the warning
```
Could not lex literal_block as "python". Highlighting skipped.
```
But, I don't get the warning when I changed it to
```rst
.. code-block:: text
```

**Comment by 2bndy5** [comment]
It looks like a jupyter notebook syntax, so you may want to look into nbsphinx extension, but I don't know if that provides a ipython3 lexer to pygments.

**Comment by mhostetter** [comment]
> I also had to change the code-block syntax for language highlighting because
>
> ```rst
> .. code-block:: python
> ```
>
> will produce the warning
>
> ```
> Could not lex literal_block as "python". Highlighting skipped.
> ```

Sorry, I forgot that since that is ipython output, the directive should be `.. code-block:: ipython`. But even raw `text` produces the same output regarding spacing.

> I was able to reproduce this using the default font. As soon as I added .. Then I get the expected output. Notice the casing in the specified font name, namely "mono" vs "Mono".

Well, damn. I wonder if other fonts I tried *silently* failed as well, i.e. didn't actually switch to the new font. I, too, get the correct result with `"Ubuntu mono"`.

Well thank you! I suppose the original issue was with `"Roboto Mono"` and not any CSS.

**Comment by 2bndy5** [comment]
I still get the warning:
```
Pygments lexer name 'ipython' is not known
```
Same with ipython3.

**Comment by mhostetter** [comment]
@2bndy5 I use these extensions. So it must be provided in there (likely the first).

```python
extensions = [
    "IPython.sphinxext.ipython_console_highlighting",
    "IPython.sphinxext.ipython_directive"
]
```

**Comment by mhostetter** [comment]
@2bndy5 from your understanding of the HTML and CSS. Is there an easy way to use a different font family in `.. code-block::` sections *only* (and leave literals and other places "code" font is used as the default)?

**Comment by 2bndy5** [comment]
you could

in RST:
```rst
.. code-block::
    :class: myCustomCSSclassName
```
in CSS:
```css
.myCustomCSSclassName code {
  font-family: "Ubuntu mono";
}
```
Just be sure you added the extra css file via the conf.py
```py
# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = ["custom_material.css"]
```

**Comment by mhostetter** [comment]
@2bndy5 excellent, thank you!!

**Comment by 2bndy5** [comment]
It would also seem that the specified font has to pulled in from google's server... This would require an advanced technique that overrides the html temple (not something I would suggest to HTML beginners). Alternatively you could

1. add the font file to your _static folder (this may be subject to font file format (.woff vs .ttf). There may be other requirements with sphinx to do this.
2. use a font universally available in most OS font face offerings (on windows I see "Noto Mono" is available)

**Comment by 2bndy5** [comment]
CSS also provides a fallback mechanism that is used when the first font family is not found

```css
.my-custom-css-class-name code {
  font-family: "Ubuntu mono", monospace; /* falls back to a generic monospace font */
}

You can specify more than 1 fallback option too.
