### ISSUE TITLE
Any chance for new release?

### ISSUE THREAD

**Issue by Novakov** [jbms/sphinx-immaterial#388]
Is there a chance for getting new official release? Fix for Sphinx 8.0.2 (https://github.com/jbms/sphinx-immaterial/commit/ddb753c6a4de58741535e0f5812e83fe4da91f19) didn't make it to latest release.

I'm aware that it is possible to depend on specific commit but awesome but complex work done in `setup.py` makes it much harder to support across entire team.

**Comment by 2bndy5** [comment]
Currently blocked by #383 because it breaks our CI (which is how we publish releases from git tags).

**Comment by 2bndy5** [comment]
Just published [v0.12.3](https://pypi.org/project/sphinx-immaterial/0.12.3/). Sorry for any inconvenience.

**Comment by 2bndy5** [comment]
FYI, any commit to main branch is published as a nightly release to [test-pypi](https://test.pypi.org/project/sphinx-immaterial/#history). Your team could have simplified their workflows by pinning to one of those releases. 😉 

@jbms It would be nicer if you yanked any non-releases-candidates on test-pypi:
- [v0.11.9](https://test.pypi.org/project/sphinx-immaterial/0.11.9/)
- [v0.11.4](https://test.pypi.org/project/sphinx-immaterial/0.11.4/)
- [v0.4.0](https://test.pypi.org/project/sphinx-immaterial/0.4.0/)
- [v0.1](https://test.pypi.org/project/sphinx-immaterial/0.1/)

That way pip will resolve to the latest pre-release when using test-pypi.

**Comment by Novakov** [comment]
> Just published [v0.12.3](https://pypi.org/project/sphinx-immaterial/0.12.3/). Sorry for any inconvenience.

Thanks a lot!
