### ISSUE TITLE
Hide toc or navigation seems not work 

### ISSUE THREAD

**Issue by zclab** [jbms/sphinx-immaterial#39]
When I try to hide table of contents sidebars or navigation, it did not work. I add the following line in markdown files

```
---
hide:
  - navigation
  - toc
---
```

Is this the right method to hide table of contents sidebars or navigation? Thanks.

**Comment by zclab** [comment]
After I modified the following code at `nav_adapt.py`, the toc or navigation can be hidded, 

```python
page = dict(
        title=page_title,
        is_homepage=(pagename == context["master_doc"]),
        toc=local_toc,
        meta={"hide": meta.get("hide", []), "revision_date": context.get("last_updated")},
        content=context.get("body"),
    )
```

**Comment by 2bndy5** [comment]
> Is this the right method to hide table of contents sidebars or navigation?

No. This is not mkdocs. This theme is for sphinx which generally uses rst (restructuredText) files. If you're using md files then you're likely using a sphinx extension to do so. In which case the meta data that can be used in mkdocs-material is not always supported in sphinx-immaterial. On that note, all the markdown extensions used by mkdocs-material are not used by sphinx-immaterial.

You can have a look at [this theme's docs to see how to customize it](https://jbms.github.io/sphinx-immaterial/customization.html).

I don't think that hiding the sidebars are a supported feature in this theme.

**Comment by 2bndy5** [comment]
I misread [this comment](https://github.com/jbms/sphinx-immaterial/issues/39#issuecomment-1056542100). You're welcome to submit a PR with your changes, but I'd ask that there be some addition to this theme's docs on how to use the metadata (in RST files).

**Comment by zclab** [comment]
Thanks for your answering. Great help.

> You can have a look at [this theme's docs to see how to customize it](https://jbms.github.io/sphinx-immaterial/customization.html).

I double checked the docs, there is no guidance to hide toc or navigation. I think I use the theme incorrectly, I did not notice the meta data that can be used in mkdocs-material is not always supported in sphinx-immaterial. 


> ```
> :hide: toc, navigation
> 
> .. or
> 
> :hide: toc
> :hide: navigation
> ```

I have tested it, seems not work. I think the code `meta={"hide": [], "revision_date": context.get("last_updated")}` at `nav_adapt.py` gives an empty `hide` meta data, it seems the meta 'hide' are not caught. 

I am not familiar with Sphinx, I am not sure if this is the reason.

> What sphinx extension are you using to use md files?

I am using [myst_parser extension](https://github.com/executablebooks/MyST-Parser) which allows to write MyST Markdown in Sphinx.

**Comment by 2bndy5** [comment]
From looking at the nav_adapt.py, I see that you can hide the toc by using 
```rst
:tocdepth: 0

..
    I'm not sure what this would look like in MD.
```
but I don't see support for hiding the navigation.

**Comment by 2bndy5** [comment]
After more discussion (in #40) about how to implement this, we've settled on
```rst
:hide-navigation:
:hide-toc:
```
Additionally, the following will still work to hide the toc
```rst
:tocdepth: 0
```

---
I had a look at the MyST parser extension, and I didn't see any explicit mention of supporting metadata. However, given the discussion in https://github.com/executablebooks/MyST-Parser/issues/286 , you could try using
```md
---
hide-navigation: true
hide-toc: true
---
```
or optionally (to just hide the toc)
```md
---
tocdepth: 0
---

**Comment by zclab** [comment]
Cool 👍, thanks !

**Comment by 2bndy5** [comment]
Is that confirming that it works with MyRST parser?

**Comment by zclab** [comment]
> Is that confirming that it works with MyRST parser?
> ```lisp
> ---
> hide-navigation: true
> hide-toc: true
> ---
> ```

Yes, it works very well.
