### ISSUE TITLE
production lists rendered incorrectly

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#46]
I noticed this a long time ago, but keep forgetting to file this issue.

An erroneous example can be seen [in our hosted docs](https://sphinx-immaterial.readthedocs.io/en/v0.7.3/additional_samples.html#production-lists)

I think the expected behavior is something that resembles a typical code-block but with cross-referencing links in certain parts of the code. I generally don't use the `productionlist` directive, but I figured I should say something.

The directive's docs are at [the Sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-productionlist)

An expected behavior can be observed from the attached simple project (uses furo theme)
[prod-list-proper.zip](https://github.com/jbms/sphinx-immaterial/files/8308599/prod-list-proper.zip)

![image](https://user-images.githubusercontent.com/14963867/159107100-9162ef2d-8623-436e-96f3-23e4c19e8bce.png)

**Comment by 2bndy5** [comment]
The problem seems to be related to misinterpreting the backticks `` ` `` within the directive's content.

**Comment by jbms** [comment]
Yeah, I'm not sure what is going on.  I noticed this issue when first putting together this theme, but since I have no use for productionlist I didn't bother to look into it more.

**Comment by 2bndy5** [comment]
I have a feeling its related to CSS in upstream not compensated for production lists' style(s) or misunderstanding the `code` element's context.

**Comment by 2bndy5** [comment]
Peeked at the [`visit_productionlist()` in Sphinx](https://github.com/sphinx-doc/sphinx/blob/4bf9f65680e37038315f6b15ad4467a0a5033f75/sphinx/writers/html5.py#L490), and it doesn't enclose the literal block in a `<code>` element. Not sure if this violates HTML5 specs, but I think this should be elevated in sphinx before we address it here, which will likely involve another monkeypatch to (or rewrite of) the visitor.

With an added `<code>` element, the productionlist directive renders in a more expected way, but the backticks within the block are treated as references and triggering warnings in the build log since there's no definition to reference. According to the Sphinx docs (which is a bit vague in its terminology), the references are supposed to be defined by other production lists (see the [python docs](https://docs.python.org/3/reference/compound_stmts.html#the-try-statement) from which the the sample snippet in OP is taken from).

<details><summary>preliminary test with patched visitor</summary>
<br>

Notice the copy button is occupying a separate line (unexpected behavior). This is likely because the literal block (even with a `<code>` element) doesn't match the structure of the output from a `visit_literal_block()` call (missing a parent `<div class="highlight">` element).

![image](https://user-images.githubusercontent.com/14963867/198814235-42971487-f219-4dd5-b2f0-f34e7f915dcf.png)

</details>

All in all, I think this directive is rather specific in usage but nonetheless interesting. I'm still exploring...

**Comment by 2bndy5** [comment]
> doesn't enclose the literal block in a &lt;code&gt; element. Not sure if this violates HTML5 specs

I've been researching, and it doesn't look like the HTML5 specs require a `code` element within a `pre` element (specs about the `pre` tag seem to be inherited from the original HTML specs). So, I don't think this is worthy of Sphinx attention; such a change may break CSS with other themes about production lists. Rather the problem (in the OP) is more specific to mkdocs-material's CSS/JS which expect there to always be a `code` element within a `pre` element. Nested `code` elements (for inline references) haven't been a problem during my tests.

I've pushed a patch to a new branch and will submit a PR for review.
