### ISSUE TITLE
 'NoneType' object has no attribute 'walk'

### ISSUE THREAD

**Issue by danwos** [jbms/sphinx-immaterial#51]
I get the following error if I try to use ``sphinx-immaterial`` with a fresh sphinx project, created by ``sphinx-quickstart``.
```
Extension error (sphinx_immaterial.nav_adapt):
Handler <function _html_page_context at 0x7f47a41e1c60> for event 'html-page-context' threw an exception (exception: 'NoneType' object has no attribute 'walk')
```
The reason is, that you need a ``toctree`` directive and at least one additional rst-file, which must be mentioned in the ``toctree`` directive.

So this **does not work** (index.rst):
```rst 
Project
=======
Test me
```
This **does also not work**:
```rst 
Project
=======
Test me

.. toctree::


```

but this **works**:
```rst 
Project
=======
Test me

.. toctree::

   page.rst

```

The problematic code is inside ``nav_adapt.py``:
```python
def _get_mkdocs_toc(
    toc_node: docutils.nodes.Node, builder: sphinx.builders.Builder
) -> List[MkdocsNavEntry]:
    """Converts a docutils toc node into a mkdocs-format JSON toc."""
    visitor = _TocVisitor(sphinx.util.docutils.new_document(""), builder)
    toc_node.walk(visitor)
    return visitor._children
```
and there toc_node can be ``None`` for small documentation projects.

**Comment by danwos** [comment]
Added really small PR to fix this issue.

**Comment by 2bndy5** [comment]
Could this be related to #41 ?

**Comment by jbms** [comment]
Thanks -- I merged your PR.

I don't think it is related to #41.
