### ISSUE TITLE
Left-side TOC collapsed into right-side TOC

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#62]
I discovered that the changes in 1373cd712c54949440bafbe4da84c818e139a1f6 cause issues with the left-side and right-side TOCs. Here is my [repo](https://github.com/mhostetter/galois) built with two consecutive commits. The individual pages in a navigation tab TOC are combined into subheading of one page.

Also, FWIW, the page title on the left-side TOC is colored differently...

Here is a chunk of `index.rst`.

```rst
.. toctree::
   :caption: Getting Started
   :hidden:

   getting-started.rst

.. toctree::
   :caption: Basic Usage
   :hidden:

   basic-usage/galois-field-classes.rst
   basic-usage/compilation-modes.rst
   basic-usage/field-element-representation.rst
   basic-usage/array-creation.rst
   basic-usage/array-arithmetic.rst
   basic-usage/linear-algebra.rst
   basic-usage/poly-creation.rst
   basic-usage/poly-arithmetic.rst

.. toctree::
   :caption: Tutorials
   :hidden:

   tutorials/intro-to-prime-fields.rst
   tutorials/intro-to-extension-fields.rst
```

### Built with e928b188b9b458654ab693fa246ca86ae79786e3

![image](https://user-images.githubusercontent.com/12112573/163694740-7188e8c9-f81c-4693-8e5c-bcc6d5d41b47.png)

### Built with 1373cd712c54949440bafbe4da84c818e139a1f6

![image](https://user-images.githubusercontent.com/12112573/163693210-c47d5775-b7ec-432b-a951-ce38fab1632f.png)

**Comment by mhostetter** [comment]
I just discovered that the TOCs only render incorrectly on the first page in the `toctree`, "Galois Field Classes" in my case.

You can reproduce this on https://galois.readthedocs.io/en/latest/basic-usage/galois-field-classes.html with these steps:

- Click the "Basic Usage" navigation tab. Notice there is no left-side TOC.

![image](https://user-images.githubusercontent.com/12112573/163694887-617436ea-de1d-45d0-bd98-dabf40f55ab0.png)

- Click "Compilation Modes" on the right-side TOC. Notice the left-side and right-side TOCs are back in place.

![image](https://user-images.githubusercontent.com/12112573/163694924-f86c200a-cfcf-476a-8dd6-e137d2dbfc62.png)

- Click "Galois Field Classes" on the left side and notice the TOCs are messed up again.

**Comment by jbms** [comment]
I will have to look into this.  The first page toc is handled specially so it makes sense that there could be a problem only affecting that.

**Comment by jbms** [comment]
Note: This issue can also be reproduced with this own theme's documentation:

Notice the incorrect collapsing of the left TOC on this page:

https://jbms.github.io/sphinx-immaterial/demo_api.html

vs this page

https://jbms.github.io/sphinx-immaterial/specimen.html

**Comment by mhostetter** [comment]
Thank you @jbms! I can confirm the merged fix resolved my issues.
