### ISSUE TITLE
Type annotation CSS was modified

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#65]
I noticed after merging #60, the CSS styling of type hints (type annotations) has changed. I believe the issue comes from the changes in `sphinx_immaterial/apidoc_formatting.py` and/or `src/assets/stylesheets/main/_api.scss`.

It seems this change is where the type hint inherits the `--md-typeset-a-color` color.

Before:
https://github.com/jbms/sphinx-immaterial/blob/8c96b11dd87e008e0e827c49c211efc401a68afd/src/assets/stylesheets/main/_api.scss#L48

After:
https://github.com/jbms/sphinx-immaterial/blob/d874316382d3413ab4b78c2563754b4b225cc525/src/assets/stylesheets/main/_api.scss#L48

### Before: 8c96b11dd87e008e0e827c49c211efc401a68afd

![image](https://user-images.githubusercontent.com/12112573/164785012-9e35f06a-0eeb-40af-bd83-ca3414444a23.png)

![image](https://user-images.githubusercontent.com/12112573/164787018-3aaa6f21-08b6-4232-a342-145cf9b99c0c.png)

### After: d874316382d3413ab4b78c2563754b4b225cc525

![image](https://user-images.githubusercontent.com/12112573/164786297-aca1e184-2fa1-447c-89d8-01d783811882.png)

![image](https://user-images.githubusercontent.com/12112573/164786235-0c26895b-7cc0-4e0d-9ff1-9f2026fe635b.png)

**Comment by jbms** [comment]
I believe this is changed back in #64.

**Comment by mhostetter** [comment]
Oh! I didn't see that PR. Yes, I confirmed the styling is reverted with the latest commit currently on #64.
