### ISSUE TITLE
`html_wrap_signatures_with_css` default value treated as a list

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#66]
I went to play with the new features from #64 on my personal project and found this error when letting `html_wrap_signatures_with_css` be it's default value (which is None and interpreted as True).
```
Extension error (sphinx_immaterial.apidoc_formatting):
Handler <function _wrap_signatures at 0x000001AC357BACB0> for event 'object-description-transform' threw an exception (exception: argument of type 'NoneType' is not iterable)
```

The fix for this is to modify https://github.com/jbms/sphinx-immaterial/blob/708cb6a0b475323cc68da29a84c771683cef37ee/sphinx_immaterial/apidoc_formatting.py#L149
into 
```py
    if isinstance(enabled, list) and domain not in enabled:
```

Just now discovering this because I assume only the list form of the option's value was last tested. Our docs is using 
https://github.com/jbms/sphinx-immaterial/blob/7f38651b16e110ac3bcd338310f6a3241c2f2e3e/docs/conf.py#L173

**Comment by jbms** [comment]
I do check for `None` in the first `if` statement but then don't properly prevent this later condition from running.  Changing the subsequent `if` statements to `elif` statements should fix the problem.
