### ISSUE TITLE
Better readthedocs integration

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#7]
I've made some mock up edits to better integrate into readthedocs hosted docs. All details can be observed at [the issue I raised upstream](https://github.com/squidfunk/mkdocs-material/issues/3104). Unfortunately, the author has no intention to support RTD. I have 1 more use case to consider before I offer a PR here: when the user disables the nav side menu.

**Comment by jbms** [comment]
The `documentation_options.js` issue is separate, I think, though I suppose the RTD extension potentially needs it.  This theme excludes that file from the output directory, but it looks like it still needs to be excluded from the HTML templates.  The reason it is excluded is that nothing seemed to use it --- it seemed to be mostly for the normal sphinx search implementation, which is not used by this theme.

As far as `$`, sphinx also includes jquery by default.  As this theme does not require it, it is excluded.

Perhaps some config options could be added to allow jquery and/or documentation_options to be retained.

Arguably if you have the version selector you may not want to show the latest release in the repo.  Not sure if there is already an option to hide that.

**Comment by jbms** [comment]
jquery is excluded in these two places:
https://github.com/jbms/sphinx-immaterial/blob/d59f75c815f7018e2a651c8b0c3741db42304c9c/sphinx_immaterial/__init__.py#L106
https://github.com/jbms/sphinx-immaterial/blob/d59f75c815f7018e2a651c8b0c3741db42304c9c/sphinx_immaterial/__init__.py#L154

You could see if removing the exclusion allows RTD to work without any other modifications to this theme.

**Comment by 2bndy5** [comment]
Great news! I went in and adjusted the sphinx_immaterial/\_\_init\_\_.py to not exclude the jquery stuff (as advised). I should mention that this is done automatically using a env var `READTHEDOCS` which is only declared on RTD's build environment. Thus no extra interaction required from the user.

# It works natively!
![image](https://user-images.githubusercontent.com/14963867/137045611-cb901198-2400-49b8-b0af-eda7fd72ac3f.png)
![image](https://user-images.githubusercontent.com/14963867/137046510-b0ee4a8a-f2e4-4c4b-91e6-fec09087b397.png)

I think I'll do some css overrides to adjust the font size and positioning of the menu (currently gets in the way of the secondary ToC). I'll try to have it "float" just below the header where the repo info is (before the secondary ToC begins).

I'm still seeing some warnings/errors in the browser's console, but they are mostly related to the search feature that this theme replaces. There is still something about google analytics and RTD's use of "ethical ads", but I'm ok with letting those be.

@jbms Your advice saved me a lot more work. Thank you!

**Comment by jbms** [comment]
Since it is so small, it is probably simplest to just always include it, rather than add the complexity of conditionally including it.

Adding an additional scss file to be included is not too big of a deal, already there are some additions to account for other sphinx-specific things.  It won't cause a lot of merge difficulties.
