### ISSUE TITLE
resolving merge conflicts with upstream v8.2.11

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#74]
This is a thread devoted to resolving merge conflicts from upstream mkdocs-material repo.

**Comment by jbms** [comment]
I pushed a commit to the `merge-upstream-v8.2.11` branch that fixes the out-of-memory issue.  You will have to run `npm install` after pulling it.

**Comment by 2bndy5** [comment]
Just when I thought I had a handle on how npm works, that commit's message makes me think I don't know enough about the package-lock file (& how it affects dep's deps). Thanks for the help!
