### ISSUE TITLE
API signature punctuation has modified CSS

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#76]
A small observation, but...

I noticed that after the changes in #60 through #73 the API signature punctuation color has changed. It used to be `var(--md-code-hl-punctuation-color)`, but now is overridden in some way. 

This can be reproduced by adding any function to your docs that has a `List[int]`, or some equivalent type hint. The `[` are considered punctuation. Notice they were gray before but are pink now.

### 8c96b11dd87e008e0e827c49c211efc401a68afd

![image](https://user-images.githubusercontent.com/12112573/165547591-34c95b8b-64c2-4163-a40f-1b874046a501.png)

### 0e0dcc8c9cc88f2d160ec80a38410547c8a904d3

![image](https://user-images.githubusercontent.com/12112573/165546385-46909a0d-e71e-4e4e-a6a3-ad91651409f4.png)

**Comment by 2bndy5** [comment]
I noticed this in the testing of #64 , but I met it with acceptance. I noticed the square brackets' color changes color when interacting with either the parent type (`Tuple[]` or `List[]`, etc) or the inner type (`[int]`, `[str]`, etc).

Are you opening this issue as an undesirable behavior?

**Comment by jbms** [comment]
Sorry --- this was not an intentional change --- we should fix that.  And I recall @2bndy5 did point this out, but I think I misinterpreted it as being a comment about the lack of cross-references from `List` and `Tuple` rather than the punctuation color.

**Comment by 2bndy5** [comment]
Yeah, I should've taken the time to word that comment better. To be clear, I wasn't too worried about the punctuation as I was the color behaving like a hyperlink (for which there was no link target).
