### ISSUE TITLE
How to provide extracopyright

### ISSUE THREAD

**Issue by duncanmmacleod** [jbms/sphinx-immaterial#81]
I've just discovered this project, and love it (I have used `sphinx-material` for a while, but this gets much closer to mkdocs-material), thanks for maintaining it!

But, I can't work out how to provide `extracopyright` in a way that actually get's built into the rendered docs. I've put together a tiny demo here

https://github.com/duncanmmacleod/test-sphinx-immaterial

but nothing I put in my `_templates/layout.html` seems to have any effect. Is this possible?

**Comment by jbms** [comment]
You should override it in `_templates/partials/footer.html` instead, I believe.

**Comment by duncanmmacleod** [comment]
> You should override it in `_templates/partials/footer.html` instead, I believe.

Ok, looking at it I think modifying `partials/copyright.html` would be easier.

But, this does ask the question of why there's a custom block `extracopyright` if it can't be used? I also see `extrafooter` defined in `partials/footer.html` - I presume, but haven't tested, that this similarly can't be used?

**Comment by 2bndy5** [comment]
> Ok, looking at it I think modifying partials/copyright.html would be easier.

I think you're correct. Please let us know your findings when you can.

The `extracopyright` block seems to have been inherited from sphinx-material theme, and it may be one of the relic features that hasn't been tested thoroughly in this theme. We're still working toward a stable state, so you're feedback will likely make it into the docs if/when this is solved. The [docs about customizing templates for this theme](https://jbms.github.io/sphinx-immaterial/customization.html#customizing-the-layout) were also inherited from sphinx-material theme and haven't seen much alterations either.

Risking what might be obvious to you, here is a link to the [sphinx docs about customizing the theme templates](https://www.sphinx-doc.org/en/master/templating.html#jinja-sphinx-templating-primer).

**Comment by 2bndy5** [comment]
oh, this seems troubling
https://github.com/jbms/sphinx-immaterial/blob/6ceccff8d865208ffbdbbe5feef814936d659835/src/partials/footer.html#L84

The `if False` seems to have been merged in from updates in mkdocs-material repo. I have to brush up on jinja syntax, but I suspect the `False` constant may be preventing `extracopyright` from being used.

**Comment by 2bndy5** [comment]
ok, using the latest release of this theme, I was able to add content to the footer.
### template override
create a file named `footer.html` in a directory called `partials` under your docs/_templates
```
docs
└ _templates
  └ partials
    └ footer.html
```
extend the theme's `partials/footer.html` and override the `extracopyright` block.
```html
{% extends "!partials/footer.html" %}
{% block extracopyright %}
  <p>EXTRA COPYRIGHT</p>
{% endblock %}
```
now build your docs. For me, this resulted in
![image](https://user-images.githubusercontent.com/14963867/166448779-3fb85901-b1b4-46bc-a1bd-3a03c86ef5ef.png)

**Comment by duncanmmacleod** [comment]
> I think you're correct. Please let us know your findings when you can.

Overwriting the copyright.html partial works just fine.

Thanks for the neat solution extending the footer partial, that sounds like the 'official' solution to the problem.

**Comment by duncanmmacleod** [comment]
It looks like mkdocs-material removed their `extracopyright` support for v8, so I presume overwriting copyright.html will be the best solution for upstream compatibility.

**Comment by 2bndy5** [comment]
re-opening as a reminder to adjust the docs.

@duncanmmacleod can point me to how you ended up doing this? The link in OP hasn't seen any modifications.

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod can point me to how you ended up doing this? The link in OP hasn't seen any modifications.

I have updated the example repo with a solution: https://github.com/duncanmmacleod/test-sphinx-immaterial/tree/79431161a9944890d48e3fb047f0712317a410f0.

**Comment by duncanmmacleod** [comment]
For full disclosure, my application here is to generate linked extensions for mkdocs-material **and** sphinx-immaterial that provide a common documentation theme across both sphinx and mkdocs projects. So my preferred solution is the one that can be implemented in both projects in as similar a way as possible, and since mkdocs-material dropped `extracopyright`, I favour the partial solution over the block one.

**Comment by 2bndy5** [comment]
Note to self: Change the copyright year for this theme's footer.
