### ISSUE TITLE
Literal shortening has issue with autodoc type hint shortening

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#82]
I love the new features in #79!! Thank you for them. 🙏 

However, I have noticed a couple minor issues. One is that `Union` and `Literal` conversions with `python_transform_type_annotations_pep604 = True` have an issue when type shortening is used with autodoc, namely the `autodoc_typehints_format = "short"` feature (here's the [docs](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints_format)).

I know that feature converts `typing.Literal` to `~typing.Literal`, which is likely where the extra ~ comes from. I've been looking at the code to try to find a quick fix, but haven't found it yet.

Here's an example ripped from my code. But any function with a literal will work to reproduce.

```python
def irreducible_poly(order: int, degree: int, method: Literal["min", "max", "random"] = "min") -> Poly:
    pass
```

### Without using `autodoc_typehints_format = "short"`

![image](https://user-images.githubusercontent.com/12112573/165965251-47080905-3195-4d8d-9e7d-6c9741b58056.png)

### Using `autodoc_typehints_format = "short"`

![image](https://user-images.githubusercontent.com/12112573/165963873-bcad40b1-3aa1-4268-8180-c0a48e418300.png)

**Comment by jbms** [comment]
Sphinx is assigning special meaning to Python syntax here, so we end up with an ast where the Subscript node (corresponding to Literal[...]) is wrapped in an Invert node.  To fix this we would need to add a `visit_Invert` method to `TypeAnnotationTransformer` to handle this case.

**Comment by mhostetter** [comment]
Oh, I see. I'm unfamiliar with `ast`, but I think I'm getting the idea now. I'm guessing the nodes are visited inner-to-outer? So `visit_Invert` would need to strip the `~` only if the inner section was `Optional`, `Union`, or `Literal`?

I found a solution/workaround which is to use `autodoc-process-siganture` to remove the `~` from those three cases only. This would only be connected if `python_transform_type_annotations_pep604 = True`. If you like this solution, I can submit a PR.

```python
def autodoc_process_signature(app, what, name, obj, options, signature, return_annotation):
    signature = modify_type_hints(signature)
    return_annotation = modify_type_hints(return_annotation)
    return signature, return_annotation

def modify_type_hints(signature):
    if signature:
        signature = signature.replace("~typing.Optional", "typing.Optional")
        signature = signature.replace("~typing.Union", "typing.Union")
        signature = signature.replace("~typing.Literal", "typing.Literal")
    return signature

def setup(app):
    app.connect("autodoc-process-signature", autodoc_process_signature)
```
