### ISSUE TITLE
Hide type hints in parameters section if `autodoc_typehints = "signature"` or `"none"`

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#88]
I just happened to notice that the type hints are displayed in the parameters section even when `autodoc_typehints = "signature"` (docs [here](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints)). The current functionality seems to be `"both"` regardless of its values.

I noticed this because I hid Sphinx's type hints from the description because they weren't formatted nicely. Your new ones are, and I'll keep them, but I still think it would be nice/proper to hide them if a user sets `autodoc_typehints = "signature"` or `"none"`.

### Example

Even with `autodoc_typehints = "signature"`, I get something like the following.

![image](https://user-images.githubusercontent.com/12112573/166118795-807319b8-e745-4381-86ab-14e52c04e32e.png)

**Comment by jbms** [comment]
It might be confusing to rely on `autodoc_typehints` since this isn't actually related to autodoc.

Instead we could have a separate option to control whether to add the type hints and default values from the signature into the parameter descriptions.

**Comment by mhostetter** [comment]
That makes sense. Again, I personally will keep them in both places, but I could see that someone may prefer an option.

**Comment by mhostetter** [comment]
I'm going to close this. I no longer want/need this feature.
