### ISSUE TITLE
mkdocs edit_url not compatible with sphinx

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#9]
I've been looking for what features work as expected to determine what config stuff should go into the docs. I happened across this code
https://github.com/jbms/sphinx-immaterial/blob/6267f13b77dacf371918aa69ea1f3caf0bec5d85/src/base.html#L297-L306

but it seems to be unaltered from the original mkdocs-material theme's _src/base.html_.

### Trying to minimize changes to base.html template
Now, I would like to pass the proper `edit_url` based on config context which is updated from [`html_page_context()`](https://github.com/jbms/sphinx-immaterial/blob/d59f75c815f7018e2a651c8b0c3741db42304c9c/sphinx_immaterial/__init__.py#L200), but I think I need to make the **assumption that the document's source file is located in the docs folder**. The source file's extension (.rst or any other supported suffix) can be fetched with the template's global variable `page_source_suffix`. Maybe there's a better way to do this, but this is what I have working so far.

<details><summary>__init__.py changes</summary>

```diff
--- sphinx_immaterial/__init__.py
+++ sphinx_immaterial/__init__.py
@@ -218,235 +218,241 @@
+    repo_url = theme_options.get("repo_url", None)
     context.update(
         config={
             "theme": theme_options,
             "site_url": theme_options.get("site_url"),
             "site_name": context["docstitle"],
-            "repo_name": theme_options.get("repo_url", None),
+            "repo_url": repo_url,
             "repo_name": theme_options.get("repo_name", None),
+            "edit_url": ""
+            if repo_url is None
+            else "/".join(
+                [repo_url.rstrip("/"), os.path.split(app.srcdir)[1], pagename]
+            ),
             "extra": {
                 "version": version_config,
                 "social": theme_options.get("social"),
                 "disqus": theme_options.get("disqus"),
                 "manifest": theme_options.get("pwa_manifest"),
             },
             "plugins": theme_options.get("plugins"),
             "google_analytics": theme_options.get("google_analytics"),
         },
         base_url=base_url,
    )
```
</details>
<details><summary>template changes</summary>

```diff
--- src/base.html
+++ src/base.html
@@ -298,306 +298,306 @@
-                {% if page.edit_url %}
+                {% if config.edit_url %}
                   <a
-                    href="{{ page.edit_url }}"
+                    href="{{ config.edit_url ~ page_source_suffix }}"
                     title="{{ lang.t('edit.link.title') }}"
                     class="md-content__button md-icon"
                   >
                     {% include ".icons/material/pencil.svg" %}
                   </a>
                 {% endif %}
```
</details>

You may have noticed that RTD has its own (probably more precise) mechanism that provides links to the document's source (see pictures in #7), but I figured I'd try to tackle this for completion (& people coming from mkdocs who've only ever used gh-pages). Here's a screenshot of the above changes' result:

![image](https://user-images.githubusercontent.com/14963867/137316635-f5dac280-2402-4de7-9642-b24a561a1f54.png)

**Comment by jbms** [comment]
You seem to have already figured it out, but you might find it interesting to look at this extension:
https://github.com/westurner/sphinxcontrib-srclinks

Alternatively you could look at the implementation used by readthedocs.

I think it would be best to avoid including a default that assumes a particular branch name or path to documentation, so your suggestion of leaving it unspecified by default sounds good.
