### ISSUE TITLE
Upload source distribution (tarball) to PyPI

### ISSUE THREAD

**Issue by duncanmmacleod** [jbms/sphinx-immaterial#96]
The latest release (0.7.1) on PyPI only includes a wheel, it would be great to have a source distribution (tarball) to enable rebuilding of sphinx-immaterial for other distributions (e.g. [conda-forge](https://conda-forge.org)). It is reasonable to add this to the github actions workflow (am happy to contribute this)?

**Comment by 2bndy5** [comment]
PRs are welcome. I should warn you that we only upload wheels because building the theme from source requires node.js v16+ -- I'm aware that node.js is available via conda-forge.

**Comment by 2bndy5** [comment]
[v0.7.2 is at your disposal on pypi](https://pypi.org/project/sphinx-immaterial/0.7.2/#files)
